#!/bin/bash

if [ $# -le 0 ];
then
        echo "hay que intocir minimo 1 parametro"
exit
fi

mensaje="hola"
primero=1

while [ -n "$1" ];
 do
        if [ $primero -eq 1 ];
then
        mensaje="$mensaje $1"

        primero=0

else
        mensaje="$mensaje, $1"
fi
shift
done
echo $mensaje"!"

